# -*- coding: utf-8 -*-
#
# Syncthing documentation build configuration file, created by
# sphinx-quickstart on Thu May 28 08:33:11 2015.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

import sys
import os
import re
from datetime import datetime
from sphinx_clarity_theme import ThemeOptions
import requests

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#sys.path.insert(0, os.path.abspath('.'))
sys.path.insert(0, os.path.abspath('_ext'))

# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
needs_sphinx = '2.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.todo',
    'sphinx.ext.extlinks',
    'edit_on_github',
    'syncthing_config',
    'sphinx.ext.graphviz',
]

edit_on_github_project = 'syncthing/docs'
edit_on_github_branch = 'main'

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix of source filenames.
source_suffix = '.rst'

# The encoding of source files.
#source_encoding = 'utf-8-sig'

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = u'Syncthing'
year = datetime.now().year
copyright = f'2014-{year}, The Syncthing Authors'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The full version, including alpha/beta/rc tags.

release = 'v2'
try:
    release = open('RELEASE', 'r').read().strip()
except FileNotFoundError:
    release = os.popen('git describe --tags --long --always').read().strip()

_git_tag = ''
try:
    _git_tag = open('TAG', 'r').read().strip()
except FileNotFoundError:
    _git_tag = os.popen('git describe --tags --exact-match').read().strip()

# The short X.Y version.
version = release.partition('-')[0]

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#language = None

# There are two options for replacing |today|: either, you set today to some
# non-false value, then it is used:
#today = ''
# Else, today_fmt is used as the format for a strftime call.
#today_fmt = '%B %d, %Y'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = ['_build', '_syncthing', 'draft', 'README.rst', 'users/faq-parts', 'venv', '.venv']

# The reST default role (used for this markup: `text`) to use for all
# documents.
#default_role = None

# If true, '()' will be appended to :func: etc. cross-reference text.
#add_function_parentheses = True

# If true, the current module name will be prepended to all description
# unit titles (such as .. function::).
#add_module_names = True

# If true, sectionauthor and moduleauthor directives will be shown in the
# output. They are ignored by default.
#show_authors = False

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# A list of ignored prefixes for module index sorting.
#modindex_common_prefix = []

# If true, keep warnings as "system message" paragraphs in the built documents.
#keep_warnings = False

# Show .. todo:: block.
todo_include_todos = True

# Configure external links.
extlinks = {
    'issue': ('https://github.com/syncthing/syncthing/issues/%s', 'issue #%s'),
    'user': ('https://github.com/%s', '@%s'),
    'commit': ('https://github.com/syncthing/syncthing/commit/%s', None),
}

# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
html_theme = "sphinx_clarity_theme"

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
# https://readcraft.io/sphinx-clarity-theme/docs/en/latest/reference/
html_theme_options: ThemeOptions = {
    "header_menu": [
        {
            "label": "Donate",
            "url": "https://syncthing.net/donations/",
        },
        {
            "label": """GitHub <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M10.303 16.652c-2.837-.344-4.835-2.385-4.835-5.028c0-1.074.387-2.235 1.031-3.008c-.279-.709-.236-2.214.086-2.837c.86-.107 2.02.344 2.708.967c.816-.258 1.676-.386 2.728-.386s1.913.128 2.686.365c.666-.602 1.848-1.053 2.708-.946c.3.581.344 2.085.064 2.815c.688.817 1.053 1.913 1.053 3.03c0 2.643-1.998 4.641-4.877 5.006c.73.473 1.224 1.504 1.224 2.686v2.235c0 .644.537 1.01 1.182.752c3.889-1.483 6.94-5.372 6.94-10.185c0-6.081-4.942-11.044-11.022-11.044c-6.081 0-10.98 4.963-10.98 11.044a10.84 10.84 0 0 0 7.112 10.206c.58.215 1.139-.172 1.139-.752v-1.719a2.8 2.8 0 0 1-1.032.215c-1.418 0-2.256-.773-2.857-2.213c-.237-.58-.495-.924-.989-.988c-.258-.022-.344-.129-.344-.258c0-.258.43-.451.86-.451c.623 0 1.16.386 1.719 1.181c.43.623.881.903 1.418.903s.881-.194 1.375-.688c.365-.365.645-.687.903-.902"/></svg>""",
            "url": "https://github.com/syncthing/syncthing",
        }
    ],
    "header_title": False,
    "edit_page_label": """Edit this page on GitHub <svg xmlns="http://www.w3.org/2000/svg" width="1.25em" height="1.25em" viewBox="0 0 24 24"><path fill="currentColor" d="M13.654 21v-2.21l5.333-5.307q.148-.13.305-.19t.315-.062q.172 0 .338.064q.165.065.301.194l.925.944q.123.148.188.308q.064.159.064.319t-.061.322t-.19.31L15.863 21zm6.885-5.94l-.926-.945zm-6 5.056h.95l3.467-3.474l-.45-.494l-.475-.47l-3.493 3.488zM6.615 21q-.691 0-1.153-.462T5 19.385V4.615q0-.69.463-1.152T6.616 3H14.5L19 7.5v2.596h-1V8h-4V4H6.616q-.231 0-.424.192T6 4.615v14.77q0 .23.192.423t.423.192h4.654v1zm11.89-4.852l-.475-.47l.925.964z"/></svg>""",
    "edit_page_url": "https://github.com/syncthing/docs/edit/main/{filename}",
    "version_select_data": requests.get("https://docs.syncthing.net/versions.json").json(),
    "version_select_current": version,
    "version_select_url": "/{version}/",
}

# The name for this set of Sphinx documents.  If None, it defaults to
# "<project> v<release> documentation".
if version == _git_tag:
    html_title = f'{project} {version} documentation'
else:
    html_title = f'{project} documentation'

# A shorter title for the navigation bar.  Default is the same as html_title.
#html_short_title = None

# The name of an image file (relative to this directory) to place at the top
# of the sidebar.
html_logo = "_static/logo-horizontal.svg"

# The name of an image file (within the static path) to use as favicon of the
# docs.  This file should be a Windows icon file (.ico) being 16x16 or 32x32
# pixels large.
html_favicon = '_static/favicon.png'

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# Add any extra paths that contain custom files (such as robots.txt or
# .htaccess) here, relative to this directory. These files are copied
# directly to the root of the documentation.
#html_extra_path = []

# If not '', a 'Last updated on:' timestamp is inserted at every page bottom,
# using the given strftime format.
html_last_updated_fmt = '%b %d, %Y'

# If true, SmartyPants will be used to convert quotes and dashes to
# typographically correct entities.
#html_use_smartypants = True

# Additional templates that should be rendered to pages, maps page names to
# template names.
#html_additional_pages = {}

# If false, no module index is generated.
#html_domain_indices = True

# If false, no index is generated.
#html_use_index = True

# If true, the index is split into individual pages for each letter.
#html_split_index = False

# If true, links to the reST sources are added to the pages.
html_show_sourcelink = False

# If true, "Created using Sphinx" is shown in the HTML footer. Default is True.
html_show_sphinx = False

# If true, "(C) Copyright ..." is shown in the HTML footer. Default is True.
html_show_copyright = False

# If true, an OpenSearch description file will be output, and all pages will
# contain a <link> tag referring to it.  The value of this option must be the
# base URL from which the finished HTML is served.
#html_use_opensearch = ''

# This is the file name suffix for HTML files (e.g. ".xhtml").
#html_file_suffix = None

# Include JavaScript files with custom functionality
html_js_files = [
    'jquery-3.7.1.min.js',
    'version_redirect.js',
]

html_css_files = ["custom.css"]

# Output file base name for HTML help builder.
htmlhelp_basename = 'Syncthingdoc'

# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    'papersize': 'a4paper',

    # The font size ('10pt', '11pt' or '12pt').
    'pointsize': '11pt',

    # Additional stuff for the LaTeX preamble.
    # 'preamble': '',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    ('intro/getting-started', u'Getting-Started.tex',
     u'Getting Started', u'The Syncthing Authors', 'manual'),
    ('users/faq', u'FAQ.tex', u'FAQ', u'The Syncthing Authors', 'manual'),
]

# The name of an image file (relative to this directory) to place at the top of
# the title page.
#latex_logo = None

# For "manual" documents, if this is true, then toplevel headings are parts,
# not chapters.
#latex_use_parts = False

# If true, show page references after internal links.
#latex_show_pagerefs = False

# If true, show URL addresses after external links.
#latex_show_urls = False

# Documents to append as an appendix to all manuals.
#latex_appendices = []

# If false, no module index is generated.
#latex_domain_indices = True


# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    ('users/syncthing', 'syncthing',
     'Syncthing',
     ['The Syncthing Authors'], 1),
    ('users/stdiscosrv', 'stdiscosrv',
     'Syncthing Discovery Server',
     ['The Syncthing Authors'], 1),
    ('users/strelaysrv', 'strelaysrv',
     'Syncthing Relay Server',
     ['The Syncthing Authors'], 1),
    ('users/config', 'syncthing-config',
     'Syncthing Configuration',
     ['The Syncthing Authors'], 5),
    ('users/ignoring', 'syncthing-stignore',
     'Prevent files from being synchronized to other nodes',
     ['The Syncthing Authors'], 5),
    ('dev/rest', 'syncthing-rest-api',
     'REST API',
     ['The Syncthing Authors'], 7),
    ('dev/events', 'syncthing-event-api',
     'Event API',
     ['The Syncthing Authors'], 7),
    ('dev/device-ids', 'syncthing-device-ids',
     'Understanding Device IDs',
     ['The Syncthing Authors'], 7),
    ('users/security', 'syncthing-security',
     'Security Principles',
     ['The Syncthing Authors'], 7),
    ('users/firewall', 'syncthing-networking',
     'Firewall Setup',
     ['The Syncthing Authors'], 7),
    ('users/versioning', 'syncthing-versioning',
     'Keep automatic backups of deleted files by other nodes',
     ['The Syncthing Authors'], 7),
    ('users/faq', 'syncthing-faq',
     'Frequently Asked Questions',
     ['The Syncthing Authors'], 7),
    ('specs/bep-v1', 'syncthing-bep',
     'Block Exchange Protocol v1',
     ['The Syncthing Authors'], 7),
    ('specs/localdisco-v4', 'syncthing-localdisco',
     'Local Discovery Protocol v4',
     ['The Syncthing Authors'], 7),
    ('specs/globaldisco-v3', 'syncthing-globaldisco',
     'Global Discovery Protocol v3',
     ['The Syncthing Authors'], 7),
    ('specs/relay-v1', 'syncthing-relay',
     'Relay Protocol v1',
     ['The Syncthing Authors'], 7),
]

# If true, show URL addresses after external links.
man_show_urls = True


# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    ('index', 'Syncthing', u'Syncthing Documentation',
     u'The Syncthing Authors', 'Syncthing', 'One line description of project.',
     'Miscellaneous'),
]

# Documents to append as an appendix to all manuals.
#texinfo_appendices = []

# If false, no module index is generated.
#texinfo_domain_indices = True

# How to display URL addresses: 'footnote', 'no', or 'inline'.
#texinfo_show_urls = 'footnote'

# If true, do not generate a @detailmenu in the "Top" node's menu.
#texinfo_no_detailmenu = False

scv_whitelist_branches = ('main',)
scv_whitelist_tags = (re.compile(r'^v1\.\d+\.\d+$'),)
scv_sort = ('semver',)

graphviz_output_format = 'svg'